### ISSUE TITLE
有关数据集处理

### ISSUE THREAD

**Issue by Ban1-cmyk** [zhiweibi/PT-GAN#1]
作者您好，对于论文中所展示的医学图像合成的实验的数据处理，论文中好像并没有仔细阐述，brats2020训练集包含369名病人的数据，测试集包含125名病人的数据。代码里所展示的貌似是对每一个.nii文件取一张切片，即第79张，请问我理解的对吗？369张切片用来训练是不是太少了？如果有哪里遗漏还希望您能指导一下。
感恩的心♥

**Comment by zhiweibi** [comment]
您好，你的理解是对的，我们只用了一张切片，我们的方法在这样的训练数据下已经取得了较好的效果，数据量已经足够，这也是我们方法的优势之一。增加切片的方法也很简单，只需要在brats_dataset.py的57-61行多加一层循环，在调用loader的时候添加更多层的切片，您可以尝试一下。
