### ISSUE TITLE
有关Pretrainmodel的读取问题

### ISSUE THREAD

**Issue by wjl1999** [zhiweibi/PT-GAN#2]
麻烦请教一下，checkpoints中只给出了300_net_DE.pth和300_net_G.pth，那么test代码中net的encoder和decoder都来自net_G.path 吗？
因为我看到net_G 中的模型是存放着encoder以及decoder的内容，但是在导入第一层decoder参数的时候就出现问题，'MultiHeadResnetEncoder' object has no attribute 'decoder'。所以帮忙看看问题？

**Comment by zhiweibi** [comment]
不好意思，上传的代码与预训练模型确实有一小部分不一致。生成器的checkpoints是由encoder和decoder分别组成的，300_net_G.pth为encoder，300_net_DE.pth为decoder。MultiHeadResnetEncoder中的self.resblock最初命名为self.decoder，但这实际上不应该算作decoder的一部分。后来在发布代码前对代码重新进行了组织，修改了部分命名，导致代码与发布的预训练模型不一致。我新建了pretrain分支，与main分支的区别仅仅是修改了部分变量名，没有对代码其他部分做任何实质性的修改，您可以用该分支代码加载预训练模型进行测试。
